### ISSUE TITLE
MacOs ARM platform support

### ISSUE THREAD

**Issue by 0xmemorygrinder** [NomicFoundation/slang#1050]
Hello,

I tried to use slang on MacOs for extracting AST of a source file and when compiling, I get an error about the ARM architecture not being supported.

Is there a lot of work to support M(1,2,3) Mac devices ? If not, I can do it if it can help

Thank you in advance for your answer

**Comment by OmarTawfik** [comment]
@0xmemorygrinder `darwin-arm64` is supported, and it has been tested on an M1 successfully: https://www.npmjs.com/package/@nomicfoundation/slang-darwin-arm64

Which arch/version are you using? can you please paste the exact error you are getting?

**Comment by 0xmemorygrinder** [comment]
I am using the latest version of macos
Also, I am using the rust crates and not the npm packages

**Comment by OmarTawfik** [comment]
User was trying to install `slang` not `slang_solidity` crate. Closing as unrelated.
