### ISSUE TITLE
Move generated index.js and index.d.ts to generated dir

### ISSUE THREAD

**Issue by AntonyBlakey** [NomicFoundation/slang#239]

**Comment by OmarTawfik** [comment]
Copied from earlier comment:

- `CodegenContext` can handle formatting, so that we stop special casing it in `.prettierignore`.
- The `package.json` can just refer to it using the `main` and `types` properties:
    - https://docs.npmjs.com/cli/v9/configuring-npm/package-json#main
    - https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by OmarTawfik** [comment]
Closed by #408
