### ISSUE TITLE
Use Result rather than Option return for dynamic Language::parse method

### ISSUE THREAD

**Issue by AntonyBlakey** [NomicFoundation/slang#241]

**Comment by OmarTawfik** [comment]
My understanding is that the current API still doesn't use a `Result<>`, but panics when the indexer fails:

```rust
    pub fn get_parser(&self, kind: ProductionKind) -> &Parser {
        &self.parsers[&kind]
    }
```

I suggest keeping this open until it is fixed.

**Comment by OmarTawfik** [comment]
Apologies. Re-opened by mistake. Closing again.
