### ISSUE TITLE
Setup automatic dependencies upgrades

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#25]
## Bots

* https://github.com/dependabot
* https://github.com/renovatebot/renovate

## Requirements

* Support the package types below.
* If not, can it be extended to add custom package types/formats below?
* If not, is it cheap to set up a nightly CI job to update them and send a PR?

## Packages (ordered by priority)

* `cargo` packages in `Cargo.toml`
* `npm` packages in `package.json`
* `python3` packages in `Pipfile`
* GitHub actions we use in `.github/workflows/**.yml`
* Hermit:
    * version of the `hermit` binary itself in `bin/hermit`
    * the commit hash of `hermit-packages` source we install stuff from
    * versions of the binaries managed by hermit (`npm`/`rustc`/etc...)

**Comment by Xanewok** [comment]
I see that the dependabot is set up for the Rust/Python/TS packages. Is there anything else left to do?

**Comment by OmarTawfik** [comment]
@Xanewok updated the description since it was a bit out of date.

Currently it is not set up. It only runs for security threats/alerts. To set it up for regular updates, we need to author and check in a `dependabot.yml` config file:

* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
