### ISSUE TITLE
Scanners should consolidate terminals in their character tries

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#365]
Not all scanners build their tries from combining children scanners.
Some are constructed by calling the scanner function, which is much slower.

We can review all such examples, and if possible, inline them.

Discovered in #364

**Comment by AntonyBlakey** [comment]
Not a bug - discuss f2f

**Comment by OmarTawfik** [comment]
Moving to beta, since it is purely perf.

**Comment by AntonyBlakey** [comment]
Obsoleted by the all-scanners-as-tries pre-FSM work
