### ISSUE TITLE
thread 'main' panicked at 'Validation should have checked that references are valid between versions'

### ISSUE THREAD

**Issue by montyly** [NomicFoundation/slang#472]
Hi,

I ran `slang_solidity parse` on a couple of valid solidity files from Slither's test suit, and it triggers this issue multiple times
```
thread 'main' panicked at 'Validation should have checked that references are valid between versions'
```

The files are in [tests/e2e/detectors/test_data](https://github.com/crytic/slither/tree/dev/tests/e2e/detectors/test_data): 
```
constable-states/0.4.25/const_state_variables.sol
constable-states/0.5.16/const_state_variables.sol
enum-conversion/0.4.2/enum_conversion.sol
external-function/0.4.25/external_function.sol
external-function/0.4.25/external_function_2.sol
external-function/0.5.16/external_function.sol
external-function/0.5.16/external_function_2.sol
immutable-states/0.4.25/immut_state_variables.sol
immutable-states/0.5.16/immut_state_variables.sol
low-level-calls/0.4.25/low_level_calls.sol
low-level-calls/0.5.16/low_level_calls.sol
reentrancy-eth/0.4.25/DAO.sol
reentrancy-no-eth/0.4.25/DAO.sol
uninitialized-fptr-cst/0.4.25/uninitialized_function_ptr_constructor.sol
uninitialized-fptr-cst/0.5.16/uninitialized_function_ptr_constructor.sol
uninitialized-fptr-cst/0.5.8/uninitialized_function_ptr_constructor.sol
unused-state/0.4.25/unused_state.sol
unused-state/0.5.16/unused_state.sol
```

I specify the correct solidity version with the `--version` flag

Am I doing something wrong?

**Comment by OmarTawfik** [comment]
Thank you for reporting! Looking into this next!

**Comment by OmarTawfik** [comment]
Identified a missing validation that I can add. Will update this issue once the fix is out. Thanks!

**Comment by OmarTawfik** [comment]
@montyly version [0.5.0](https://github.com/NomicFoundation/slang/releases/tag/v0.5.0) was just released with the fixes. The `test_data` folder linked above is now parsing correctly. Please let me know if you see any other issues.
