### ISSUE TITLE
[Bug] Rust crate example in docs is incorrect

### ISSUE THREAD

**Issue by DrakeEvans** [NomicFoundation/slang#520]
The rust example in the docs is not correct.  At a minimum there is no import of Version from semvar.  Additionally, Language is now at the top level of the api not nested under syntax

See https://github.com/DrakeEvans/slang-playground/blob/master/src/main.rs for my attempt at a workaround, specifically lines 6 and 8

**Comment by OmarTawfik** [comment]
Fixed by #516
Thank you for reporting!

**Comment by OmarTawfik** [comment]
Thank you! Both pages have been updated:

- https://nomicfoundation.github.io/slang/user-guide/cargo-crate/
- https://nomicfoundation.github.io/slang/user-guide/npm-package/
