### ISSUE TITLE
Allow keywords to overlap identifiers

### ISSUE THREAD

**Issue by AntonyBlakey** [NomicFoundation/slang#568]
This is valid code in 0.4.21:

```solidity
contract ClientReceipt {
    event Deposit();
    function deposit() public payable {
        uint256 emit;
        emit Deposit();
    }
}
```

The key thing is that the emit statement is enabled from 0.4.21, but emit is still valid as an identifier. We currently cannot handle this, and it makes it impossible to compute over the versioning of tokens vs. identifiers.

**Comment by Xanewok** [comment]
https://docs.soliditylang.org/en/v0.8.21/grammar.html#a4.SolidityParser.identifier

In 0.8.21 `from`, `error`, `revert` and `global` can also overlap:

```solidity
pragma solidity ^0.8.21;

contract Contract {
    error MyError();

    function deposit() public payable {
        uint256 error;
        uint256 from;
        uint256 revert;
        uint256 global;

        revert MyError();
    }
}
```
