### ISSUE TITLE
Cursor/Node API suggestions

### ISSUE THREAD

**Issue by DrakeEvans** [NomicFoundation/slang#583]
Hi I have been using the current version for some tooling and wanted to suggest some API additions.

On RuleNode and TokenNode, it would be nice to be able to create a cursor
Given some TokenNode of kind Identifier, I would like to find the definition in the larger parse tree
Given some RuleNode, I would like a `reconstruct()` function which generates the original syntax from the children tokens
Given some RuleNode, find children with a predicate or matching a kind

**Comment by AntonyBlakey** [comment]
> On RuleNode and TokenNode, it would be nice to be able to create a cursor
Will do

> Given some TokenNode of kind Identifier, I would like to find the definition in the larger parse tree
This is binding analysis, which is coming

> Given some RuleNode, I would like a reconstruct() function which generates the original syntax from the children tokens
Will do.

> Given some RuleNode, find children with a predicate or matching a kind
```rust
some_rule_node::cursor().find_matching(...)
some_rule_node::cursor().find_token_matching(...)
some_rule_node::cursor().find_rule_matching(...)
some_rule_node::cursor().find_token_with_kind(kind)
some_rule_node::cursor().find_rule_with_kind(kind)
```

all of which just requires `cursor()` on `RuleNode`

**Comment by Xanewok** [comment]
About this point
> On RuleNode and TokenNode, it would be nice to be able to create a cursor

Could you tell me if you're dealing with `Rc`-wrapped enum variants or bare `RuleNode`/`TokenNode`?
