### ISSUE TITLE
Support Solidity versions up to 0.8.22

### ISSUE THREAD

**Issue by Xanewok** [NomicFoundation/slang#632]
The new versions are 0.8.20, 0.8.21 and 0.8.22.

In terms of the language itself:

https://soliditylang.org/blog/2023/05/10/solidity-0.8.20-release-announcement
- N/A

https://soliditylang.org/blog/2023/07/19/solidity-0.8.21-release-announcement/
- [ ] Allow qualified access to events from other contracts.
- [ ] Relax restrictions on initialization of immutable variables. Reads and writes may now happen at any point at construction time outside of functions and modifiers. Explicit initialization is no longer mandatory.

https://soliditylang.org/blog/2023/10/25/solidity-0.8.22-release-announcement
- [x] Allow defining events at file level - #648

**Comment by OmarTawfik** [comment]
passing to @AntonyBlakey for the remaining items (semantics).

**Comment by AntonyBlakey** [comment]
This issue is about updating our spec, but as far as binding is concerned, there is nothing to update because binding doesn't exist, so it's only applicable to syntax, which is done.
