### ISSUE TITLE
Empty tuple decontruction is wrongly parsed as correct

### ISSUE THREAD

**Issue by Xanewok** [NomicFoundation/slang#671]
This happens because we use a Separated grammar node parsing an Optional item. Since a missing item is treated as a succesful parse, this doesn't fail.

We should make sure to support parsing `(, ...)` with at least a single item and/or comma.

For more context:
- `() = ()` is parsed by Slang as correct but solc rejects it - tuple deconstruction can't be empty
- `(,) = ()` is rejected by solc at parse level; at least one item should not be skipped/"empty"
- ` (a,,)`,`(,a,)`,`(,,a)` are all valid deconstructions

**Comment by OmarTawfik** [comment]
Discussed f2f: let's keep it as-is, and leave such validation to type checking.
