### ISSUE TITLE
prevent empty `SKIPPED` nodes in the tree

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#700]
We insert those when there are failures, even if no text was actually skipped. Then we detect the precense of those during parsing (using a recursive cursor search) to check the validity/rank different parse results. Example:

https://github.com/NomicFoundation/slang/blob/7a3c1fbe794055c35faaeddcb9dc8814cdd5c91e/crates/solidity/testing/snapshots/cst_output/UsingDirective/destructure_empty/generated/0.8.13-failure.yml#L22-L25

This has a few issues:

- The empty `SKIPPED` token is confusing to see in the output, since nothing is actually skipped, and the returning tree is complete (regardless of errors).
- Its presence will prevent us from creating AST nodes for such trees, when it is actually valid.
- There are multiple places in parser where it creates a cursor to recursively assert some condition for all children of the current node. This incurs a big performance hit, which increases non-linearly with large trees.

Maybe we can store that info (a boolean flag?) on the parse result instead? That would eliminate the above issues, and keep the tree intact.

Possibly related to #507

**Comment by OmarTawfik** [comment]
Passing to @Xanewok for triage.

**Comment by Xanewok** [comment]
Related to #835
