### ISSUE TITLE
Emit trivia as sibling tokens and don't generate a `RuleKind` for it

### ISSUE THREAD

**Issue by Xanewok** [NomicFoundation/slang#737]
As discussed f2f.

- [ ] Remove `LeadingTrivia` and `TrailingTrivia` non-terminals.
- [ ] Include the underlying trivia as siblings to the other rules/tokens in the parent directly.
- [ ] Use `FieldName::LeadingTrivia` and `FieldName::TrailingTrivia` for the promoted siblings.
- [ ] Remove `fn is_trivia()` for `RuleKind`, since it is impossible for any variant.
- [ ] Implement `fn is_trivia()` correctly for `TokenKind` based on `Item::Trivia`, instead of returning `false`. (#862)

**Comment by OmarTawfik** [comment]
@Xanewok I think this is already part of #640 ?
