### ISSUE TITLE
Disallow dots in user-defined Yul identifiers starting from 0.7.0

### ISSUE THREAD

**Issue by Xanewok** [NomicFoundation/slang#743]
https://docs.soliditylang.org/en/v0.8.22/070-breaking-changes.html#inline-assembly

> Disallow . in user-defined function and variable names in inline assembly. It is still valid if you use Solidity in Yul-only mode.

**Comment by OmarTawfik** [comment]
I think it is a different language at this point. One maybe we can tackle once we have language embedding?
Not sure how much it is used though. Maybe we can just disallow it in Solidity for now.

**Comment by OmarTawfik** [comment]
Also: https://soliditylang.org/blog/2019/04/30/solidity-0.5.8-release-announcement

> Yul: Support . as part of identifiers.
