### ISSUE TITLE
using references in the public API

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#820]
## Incoming

Can we accept a reference to the source string in `Language::parse()` instead of owning it? using shared memory?
Is it worth it to avoid the copies in case of large strings?

## Outgoing

Many API calls currently involve cloning and returning an `Rc<T>` needlessly, rather than returning `&T`. We should review and convert them where needed.

- More context: https://github.com/NomicFoundation/slang/pull/753#discussion_r1466040079

**Comment by AntonyBlakey** [comment]
> Many API calls currently involve cloning and returning an `Rc<T>` needlessly, rather than returning `&T`. We should review and convert them where needed.

Not sure about that. We should maybe return `&Rc<T>`, to enable sharing, which you cannot do with a raw reference.
