### ISSUE TITLE
CST queries documentation

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#915]
- Creating/using queries from cursors/trees
- Query Syntax
- Code Examples

**Comment by Xanewok** [comment]
* https://github.com/AntonyBlakey/slang/blob/AntonyBlakey/integrate-stack-graphs/documentation/public/user-guide/concepts.md
* https://github.com/AntonyBlakey/slang/blob/AntonyBlakey/integrate-stack-graphs/documentation/public/user-guide/query-language.md
