### ISSUE TITLE
Unsupported stack assignment for solidity version bellow 0.5.0

### ISSUE THREAD

**Issue by Janther** [NomicFoundation/slang#984]
I'm working on adding slang as an optional parser for `prettier-plugin-solidity`.

I discovered this syntax that is a bit obscure since there weren't many examples in the documentation even when it was allowed.

In versions prior to `0.5.0`, stack assignment existed and the following code did compile.

```
contract AssemblyStackAssignment {
    function f() public returns(uint y) {
        assembly {
            4 =: y
        }
    }
}
```

**Comment by OmarTawfik** [comment]
Thanks for the report. Looking into it!
